[functions.send-notifications]
enabled = true
verify_jwt = true
import_map = "./functions/send-notifications/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-notifications/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-notifications/*.html" ]

[functions.schedule-notifications]
enabled = true
verify_jwt = true
import_map = "./functions/schedule-notifications/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/schedule-notifications/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/schedule-notifications/*.html" ]

[functions.delete-user]
enabled = true
verify_jwt = true
entrypoint = "./functions/delete-user/index.ts"

[functions.fatsecret-proxy]
enabled = true
verify_jwt = true
import_map = "./functions/fatsecret-proxy/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fatsecret-proxy/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fatsecret-proxy/*.html" ]

[functions.process-withgemini]
enabled = true
verify_jwt = false
import_map = "./functions/process-withgemini/deno.json"
entrypoint = "./functions/process-withgemini/index.ts"
