arb-dir: lib/l10n
output-dir: lib/l10n/generated
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: lib/l10n/untranslated.txt
synthetic-package: false
nullable-getter: false