// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///    options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqNLm3oFQinnrr75D4m28hWnRnPjCXJsg',
    appId: '1:116498755817:android:df411ae69473290d6fc078',
    messagingSenderId: '116498755817',
    projectId: 'macrobalance-18139',
    storageBucket: 'macrobalance-18139.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdUI4sL1_7dFCq7PA7h-ND58hwHP51tKw',
    appId: '1:116498755817:ios:0a16163fc5b9dcb76fc078',
    messagingSenderId: '116498755817',
    projectId: 'macrobalance-18139',
    storageBucket: 'macrobalance-18139.firebasestorage.app',
    iosBundleId: 'app.macrobalance.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdUI4sL1_7dFCq7PA7h-ND58hwHP51tKw',
    appId: '1:116498755817:ios:303ad3bf4d5855606fc078',
    messagingSenderId: '116498755817',
    projectId: 'macrobalance-18139',
    storageBucket: 'macrobalance-18139.firebasestorage.app',
    iosBundleId: 'com.example.macrotracker',
  );

}